### ISSUE TITLE
Can't resize since the last Discord update

### ISSUE THREAD

**Issue by Hexacontakaitric** [kosshishub/CompactGuilds-BD-plugin#4]
The sidebar still slides same as before, but I can't resize Discord at all. My friend has the same problem.

By the way, thank you so much for this plugin. I love it.

**Comment by kosshi-net** [comment]
There appears to be some limitation added to the minimum window size in the last update, but resizing otherwise works just fine on my computers. You cannot make the window larger?

I do want to find a way to remove or change these new minimum window size restrictions, i'll be doing this soon™. This plugin's purpose is to make discord usable on low resolutions and window widths.

EDIT: ``require('electron').remote.getCurrentWindow().setMinimumSize(x, y)``, i'll be adding options for this to the plugin.

**Comment by Hexacontakaitric** [comment]
Yes, it's definitely the minimum window size restrictions that are causing the issue. Sometimes I watch shows or movies online with friends and we use Discord to live chat. With your plugin, it was easy to shrink Discord and leave it on the far side of the screen, but the new update prevents this.

Thanks so much for the quick response! I hope it's not something that's too difficult to fix.

**Comment by kosshi-net** [comment]
Done.
